# This file has been generated by node2nix 1.11.1. Do not edit!

{ nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? [ ] }:

let
  sources = {
    "@digitalbazaar/http-client-3.4.1" = {
      name = "_at_digitalbazaar_slash_http-client";
      packageName = "@digitalbazaar/http-client";
      version = "3.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@digitalbazaar/http-client/-/http-client-3.4.1.tgz";
        sha512 = "Ahk1N+s7urkgj7WvvUND5f8GiWEPfUw0D41hdElaqLgu8wZScI8gdI0q+qWw5N1d35x7GCRH2uk9mi+Uzo9M3g==";
      };
    };
    "@fastify/busboy-2.1.1" = {
      name = "_at_fastify_slash_busboy";
      packageName = "@fastify/busboy";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@fastify/busboy/-/busboy-2.1.1.tgz";
        sha512 = "vBZP4NlzfOlerQTnba4aqZoMhE/a9HY7HRqoOPaETQcSQuWEIyZMHGfVu6w9wGtGK5fED5qRs2DteVCjOH60sA==";
      };
    };
    "@xmldom/xmldom-0.8.10" = {
      name = "_at_xmldom_slash_xmldom";
      packageName = "@xmldom/xmldom";
      version = "0.8.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/@xmldom/xmldom/-/xmldom-0.8.10.tgz";
        sha512 = "2WALfTl4xo2SkGCYRt6rDTFfk9R1czmBvUQy12gK2KuRKIpWEhcbbzy8EZXtz/jkRqHX8bFEc6FC1HjX4TUWYw==";
      };
    };
    "abort-controller-3.0.0" = {
      name = "abort-controller";
      packageName = "abort-controller";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/abort-controller/-/abort-controller-3.0.0.tgz";
        sha512 = "h8lQ8tacZYnR3vNQTgibj+tODHI5/+l06Au2Pcriv/Gmet0eaj4TwWH41sO9wnHDiQsEj19q0drzdWdeAHtweg==";
      };
    };
    "canonicalize-1.0.8" = {
      name = "canonicalize";
      packageName = "canonicalize";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/canonicalize/-/canonicalize-1.0.8.tgz";
        sha512 = "0CNTVCLZggSh7bc5VkX5WWPWO+cyZbNd07IHIsSXLia/eAq+r836hgk+8BKoEh7949Mda87VUOitx5OddVj64A==";
      };
    };
    "commander-11.1.0" = {
      name = "commander";
      packageName = "commander";
      version = "11.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-11.1.0.tgz";
        sha512 = "yPVavfyCcRhmorC7rWlkHn15b4wDVgVmBA7kV4QVBsF7kv/9TKJAbAXVTxvTnwP8HHKjRCJDClKbciiYS7p0DQ==";
      };
    };
    "content-type-1.0.5" = {
      name = "content-type";
      packageName = "content-type";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-type/-/content-type-1.0.5.tgz";
        sha512 = "nTjqfcBFEipKdXCv4YDQWCfmcLZKm81ldF0pAopTvyrFGVbcR6P/VAAd5G7N+0tTr8QqiU0tFadD6FK4NtJwOA==";
      };
    };
    "data-uri-to-buffer-4.0.1" = {
      name = "data-uri-to-buffer";
      packageName = "data-uri-to-buffer";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/data-uri-to-buffer/-/data-uri-to-buffer-4.0.1.tgz";
        sha512 = "0R9ikRb668HB7QDxT1vkpuUBtqc53YyAwMwGeUFKRojY/NWKvdZ+9UYtRfGmhqNbRkTSVpMbmyhXipFFv2cb/A==";
      };
    };
    "event-target-shim-5.0.1" = {
      name = "event-target-shim";
      packageName = "event-target-shim";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/event-target-shim/-/event-target-shim-5.0.1.tgz";
        sha512 = "i/2XbnSz/uxRCU6+NdVJgKWDTM427+MqYbkQzD321DuCQJUqOuJKIA0IM2+W2xtYHdKOmZ4dR6fExsd4SXL+WQ==";
      };
    };
    "fetch-blob-3.2.0" = {
      name = "fetch-blob";
      packageName = "fetch-blob";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fetch-blob/-/fetch-blob-3.2.0.tgz";
        sha512 = "7yAQpD2UMJzLi1Dqv7qFYnPbaPx7ZfFK6PiIxQ4PfkGPyNyl2Ugx+a/umUonmKqjhM4DnfbMvdX6otXq83soQQ==";
      };
    };
    "formdata-polyfill-4.0.10" = {
      name = "formdata-polyfill";
      packageName = "formdata-polyfill";
      version = "4.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/formdata-polyfill/-/formdata-polyfill-4.0.10.tgz";
        sha512 = "buewHzMvYL29jdeQTVILecSaZKnt/RJWjoZCF5OW60Z67/GmSLBkOFM7qh1PI3zFNtJbaZL5eQu1vLfazOwj4g==";
      };
    };
    "get-stdin-9.0.0" = {
      name = "get-stdin";
      packageName = "get-stdin";
      version = "9.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-stdin/-/get-stdin-9.0.0.tgz";
        sha512 = "dVKBjfWisLAicarI2Sf+JuBE/DghV4UzNAVe9yhEJuzeREd3JhOTE9cUaJTeSa77fsbQUK3pcOpJfM59+VKZaA==";
      };
    };
    "iri-1.3.1" = {
      name = "iri";
      packageName = "iri";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/iri/-/iri-1.3.1.tgz";
        sha512 = "CpzxCf3ycTphqF2hQRQAp25yK7+XM1iMJHUoJbFiQDLt70hYC+vUlrgQXuhzPrLNMuejhV0VelFp8zQmtqgAxA==";
      };
    };
    "jsonld-8.3.2" = {
      name = "jsonld";
      packageName = "jsonld";
      version = "8.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonld/-/jsonld-8.3.2.tgz";
        sha512 = "MwBbq95szLwt8eVQ1Bcfwmgju/Y5P2GdtlHE2ncyfuYjIdEhluUVyj1eudacf1mOkWIoS9GpDBTECqhmq7EOaA==";
      };
    };
    "jsonld-cli-2.0.0" = {
      name = "jsonld-cli";
      packageName = "jsonld-cli";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonld-cli/-/jsonld-cli-2.0.0.tgz";
        sha512 = "QRFn5SeP8hYfCMJobLcQwTRQaAbCYSTNwNQhTLJtOn5eub6d/HAhs2J6nJO7dmKy7siENmF4LbsC0JrNr39FxQ==";
      };
    };
    "jsonld-request-2.0.1" = {
      name = "jsonld-request";
      packageName = "jsonld-request";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonld-request/-/jsonld-request-2.0.1.tgz";
        sha512 = "nV6iFlTHVrgwbnKFLpMJEcuEgwpf2hU8qH6wkcpIDHJKFy77WetKNcEr6M85Z6xN+9D6i6wOWNVDVlNn7749EQ==";
      };
    };
    "ky-0.33.3" = {
      name = "ky";
      packageName = "ky";
      version = "0.33.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ky/-/ky-0.33.3.tgz";
        sha512 = "CasD9OCEQSFIam2U8efFK81Yeg8vNMTBUqtMOHlrcWQHqUX3HeCl9Dr31u4toV7emlH8Mymk5+9p0lL6mKb/Xw==";
      };
    };
    "ky-universal-0.11.0" = {
      name = "ky-universal";
      packageName = "ky-universal";
      version = "0.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ky-universal/-/ky-universal-0.11.0.tgz";
        sha512 = "65KyweaWvk+uKKkCrfAf+xqN2/epw1IJDtlyCPxYffFCMR8u1sp2U65NtWpnozYfZxQ6IUzIlvUcw+hQ82U2Xw==";
      };
    };
    "lru-cache-6.0.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz";
        sha512 = "Jo6dJ04CmSjuznwJSS3pUeWmd/H0ffTlkXXgwZi+eq1UCmqQwCh+eLsYOYCwY991i2Fah4h1BEMCx4qThGbsiA==";
      };
    };
    "node-domexception-1.0.0" = {
      name = "node-domexception";
      packageName = "node-domexception";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-domexception/-/node-domexception-1.0.0.tgz";
        sha512 = "/jKZoMpw0F8GRwl4/eLROPA3cfcXtLApP0QzLmUT/HuPCZWyB7IY9ZrMeKw2O/nFIqPQB3PVM9aYm0F312AXDQ==";
      };
    };
    "node-fetch-3.3.2" = {
      name = "node-fetch";
      packageName = "node-fetch";
      version = "3.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch/-/node-fetch-3.3.2.tgz";
        sha512 = "dRB78srN/l6gqWulah9SrxeYnxeddIG30+GOqK/9OlLVyLg3HPnr6SqOWTWOXKRwC2eGYCkZ59NNuSgvSrpgOA==";
      };
    };
    "rdf-4.1.1" = {
      name = "rdf";
      packageName = "rdf";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/rdf/-/rdf-4.1.1.tgz";
        sha512 = "WEXBQmMXubplwnpcL6Wo184LkAXvTaMJYxxXoTlBr4SM7XhIx3BVjltrrbh8ARTmwBthuI7p2vkv6m3rKNucgw==";
      };
    };
    "rdf-canonize-3.4.0" = {
      name = "rdf-canonize";
      packageName = "rdf-canonize";
      version = "3.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/rdf-canonize/-/rdf-canonize-3.4.0.tgz";
        sha512 = "fUeWjrkOO0t1rg7B2fdyDTvngj+9RlUyL92vOdiB7c0FPguWVsniIMjEtHH+meLBO9rzkUlUzBVXgWrjI8P9LA==";
      };
    };
    "rdfa-0.0.10" = {
      name = "rdfa";
      packageName = "rdfa";
      version = "0.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/rdfa/-/rdfa-0.0.10.tgz";
        sha512 = "/n8BSzgcZpa1kmDZcWCJ/SPRdvKTVA8WpHye5QvkOfswe5wfJ4GfSHtQ/D2yeeV18hvZNWLnyot+9yYNNSp1zw==";
      };
    };
    "setimmediate-1.0.5" = {
      name = "setimmediate";
      packageName = "setimmediate";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/setimmediate/-/setimmediate-1.0.5.tgz";
        sha512 = "MATJdZp8sLqDl/68LfQmbP8zKPLQNV6BIZoIgrscFDQ+RsvK/BxeDQOgyxKKoh0y/8h3BqVFnCqQ/gd+reiIXA==";
      };
    };
    "undici-5.28.4" = {
      name = "undici";
      packageName = "undici";
      version = "5.28.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/undici/-/undici-5.28.4.tgz";
        sha512 = "72RFADWFqKmUb2hmmvNODKL3p9hcB6Gt2DOQMis1SEBaV6a4MH8soBvzg+95CYhCKPFedut2JY9bMfrDl9D23g==";
      };
    };
    "web-streams-polyfill-3.3.3" = {
      name = "web-streams-polyfill";
      packageName = "web-streams-polyfill";
      version = "3.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/web-streams-polyfill/-/web-streams-polyfill-3.3.3.tgz";
        sha512 = "d2JWLCivmZYTSIoge9MsgFCZrt571BikcWGYkjC1khllbTeDlGqZ2D8vD8E/lJa8WGWbb7Plm8/XJYV7IJHZZw==";
      };
    };
    "web-streams-polyfill-4.0.0" = {
      name = "web-streams-polyfill";
      packageName = "web-streams-polyfill";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/web-streams-polyfill/-/web-streams-polyfill-4.0.0.tgz";
        sha512 = "0zJXHRAYEjM2tUfZ2DiSOHAa2aw1tisnnhU3ufD57R8iefL+DcdJyRBRyJpG+NUimDgbTI/lH+gAE1PAvV3Cgw==";
      };
    };
    "yallist-4.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
        sha512 = "3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
      };
    };
  };
  args = {
    name = "jsonld-cli";
    packageName = "jsonld-cli";
    version = "2.0.0";
    src = ./.;
    dependencies = [
      sources."@digitalbazaar/http-client-3.4.1"
      sources."@fastify/busboy-2.1.1"
      sources."@xmldom/xmldom-0.8.10"
      sources."abort-controller-3.0.0"
      sources."canonicalize-1.0.8"
      sources."commander-11.1.0"
      sources."content-type-1.0.5"
      sources."data-uri-to-buffer-4.0.1"
      sources."event-target-shim-5.0.1"
      (sources."fetch-blob-3.2.0" // {
        dependencies = [
          sources."web-streams-polyfill-3.3.3"
        ];
      })
      sources."formdata-polyfill-4.0.10"
      sources."get-stdin-9.0.0"
      sources."iri-1.3.1"
      sources."jsonld-8.3.2"
      sources."jsonld-cli-2.0.0"
      sources."jsonld-request-2.0.1"
      sources."ky-0.33.3"
      sources."ky-universal-0.11.0"
      sources."lru-cache-6.0.0"
      sources."node-domexception-1.0.0"
      sources."node-fetch-3.3.2"
      sources."rdf-4.1.1"
      sources."rdf-canonize-3.4.0"
      sources."rdfa-0.0.10"
      sources."setimmediate-1.0.5"
      sources."undici-5.28.4"
      sources."web-streams-polyfill-4.0.0"
      sources."yallist-4.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = { };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ]
        args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
